import os, sys, time
# Coded by github.com/singhvijayp
# Copy with credits

R="\033[1;31m"
G="\033[0;32m"

time.sleep(1)
os.system("clear")
print (R+"""
      _ ____ ____ _  _ _  _ ____ _  _
      | |__/ |  | |\ | |\/| |__| |\ |
      | |  \ |__| | \| |  | |  | | \|
"""    + G+"""              v2.0, Dev: @singhvijayp """)
time.sleep(2)
print("  ")
print(" \033[1;36mInstall the tool by their respective no. ")
print("  ")
time.sleep(2)
print("             [01] AdvPhishing ")
print("             [02] ADXdefacer ")
print("             [03] Bash-Lock ")
print("             [04] Bull-Attack ")
print("             [05] Crazy-Banner ")
print("             [06] Cute-Termux ")
print("             [07] EHZ ")
print("             [08] H-Cam2 ")
print("             [09] Hacktronian ")
print("             [10] HiddenEye ")
print("             [11] IP-FY ")
print("             [12] TermBase ")
print("             [13] MailDiya ")
print("             [14] Mr.Bat ")
print("             [15] Optiva-Framework ")
print("             [16] Pass-X ")
print("             [17] ProxyGen ")
print("             [18] ReconDog ")
print("             [19] RED_HAWK ")
print("             [20] STARK3.0 ")
print("             [21] TBomb ")
print("             [22] Termux-Banner ")
print("             [23] Termux-Killer ")
print("             [24] Termux-Lazyscript ")
print("             [25] Termux-login ")
print("             [26] Termux-speak ")
print("             [27] Th3inspector ")
print("             [28] T-LOAD ")
print("             [29] TM-scanner ")
print("             [30] TermDistro ")
print("             [31] Virus4 ")
print("             [32] X-Attack ")
print("             [33] anon-trap ")
print("             [34] blackeye ")
print("             [35] excuseme ")
print("             [36] facebash ")
print("             [37] fish ")
print("             [38] grabcam ")
print("             [39] hacklock ")
print("             [40] hammer ")
print("             [41] inshackle ")
print("             [42] instahack ")
print("             [43] instashell ")
print("             [44] ipdrone ")
print("             [45] kalimux ")
print("             [46] lazybee ")
print("             [47] lazymux ")
print("             [48] locator ")
print("             [49] lockphish ")
print("             [50] metasploit ")
print("             [51] mr.tracker ")
print("             [52] m-wiz ")
print("             [53] nexphisher ")
print("             [54] ohmyzsh ")
print("             [55] p-gen ")
print("             [56] routersploit ")
print("             [57] sayhello ")
print("             [58] seeker ")
print("             [59] shellphish ")
print("             [60] sms-scammer ")
print("             [61] sqlmap ")
print("             [62] tmvenom ")
print("             [63] phonesploit ")
print("             [64] tweetshell ")
print("             [65] userrecon ")
print("             [66] websploit ")
print("             [67] weeman ")
print("             [68] wifite ")
print("             [69] wifite2 ")
print("             [70] zphisher ")
print("             [00] Exit ")
print("  ")
k = input(" \033[1;31mEnter any option\033[0;0m : ")
if k == "01" or k == "1" :
               print(" Installing AdvPhishing... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/Ignitetch/AdvPhishing.git && cd AdvPhishing && chmod 777 start.sh && ./start.sh && ./An-AdvPhishing.sh")
elif k == "02" or k == "2" :
               print("Installing ADXdefacer... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/CharlieTheHack1/ADXdefacer.git && cd ADXdefacer && pip2 install requests && python2 adx.py")
elif k == "03" or k == "3" :
               print("Installing Bash-Lock...")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/Bhai4You/Bash-Lock.git && cd Bash-Lock && bash Bash-Lock.sh")
elif k == "04" or k == "4" :
               print("Installing Bull-Attack... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/Bhai4You/Bull-Attack.git && cd Bull-Attack && chmod +x B-Attack.py")
elif k == "05" or k == "5" :
               print("Installing Crazy-Banner... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/Bhai4You/Crazy-Banner.git && chmod +x requirement.sh c-banner.sh && bash c-banner.sh")
elif k == "06" or k == "6" :
               print("Installing Cute-Termux... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/Charliethehack1/Cute-Termux.git && cd Cute-Termux && chmod +x * && ./setup.sh")
elif k == "07" or k == "7" :
               print("Installing EHZ...")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/Ethical-Hacking-Zone/EHZ.git && cd EHZ && bash ps.sh")
elif k == "08" or k == "8" :
               print("Installing H-Cam2...")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/rooted-cyber/H-Cam2.git && cd H-Cam2 && chmod +x * && ./H-Cam2.sh")
elif k == "09" or k == "9" :
               print("Installing Hacktronian... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/thehackingsage/hacktronian.git && cd hacktronian && chmod +x hacktronian.py && python hacktronian.py")
elif k == "10" :
               print("Installing HiddenEye... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python php curl openssh grep -y && cd && git clone https://github.com/DarkSecDevelopers/HiddenEye.git && cd HiddenEye && pip install requests && python HiddenEye.py")
elif k == "11" :
               print("Installing IP-FY... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/T4P4N/IP-FY.git&& cd IP-FY && pip install requests")
               print("python ipfy.py -t (IP address of Target)")
elif k == "12" :
               print("Installing TermBase... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git && cd && git clone https://github.com/singhvijayp/TermBase.git && cd TermBase && bash term.sh")
elif k == "13" :
               print("Installing MailDiya... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && git clone https://github.com/tuhin1729/MailDiya.git && cd MailDiya && pip2 install -r requirements.txt && python2 maildiya.py")
elif k == "14" :
               print("Installing Mr.Bat... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/Bhai4You/Mr.Bat.git && cd Mr.Bat && python2 mr-bat.py")
elif k == "15" :
               print("Installing Optiva-Framework... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/joker25000/Optiva-Framework.git && cd Optiva-Framework && bash installer.sh && python2 optiva.py")
elif k == "16" :
               print("Installing Pass-X... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt-get update && apt-get upgrade -y && apt install python git -y && cd && git clone https://github.com/CharlieTheHack1/Pass-X.git && cd Pass-X && python2 Pass-X.py")
elif k == "17" :
               print("Installing ProxyGen... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/tuhin1729/ProxyGen.git && cd ProxyGen && pip2 install -r requirements.txt && python3 proxygen.py")
elif k == "18" :
               print("Installing ReconDog... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/s0md3v/ReconDog.git && cd ReconDog && ")
elif k == "19" :
               print("Installing RED_HAWK... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git php -y && cd && git clone https://github.com/RED_HAWK.git && cd RED_HAWK && php rhwak.php")
elif k == "20" :
               print("Installing STARK3.0... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/aniketstark/STARK3.0.git && cd STARK3.0 && python2 stark.py")
elif k == "21" :
               print("Installing TBomb... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/TheSpeedX/TBomb.git && cd TBomb && python bomber.py") 
elif k == "22" :
               print("Installing Termux-Banner... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/Bhai4You/Termux-Banner.git && chmod +x requirement.sh c-banner.sh && bash c-banner.sh") 
elif k == "23" :
               print("Installing Termux-Killer... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/Bhai4You/Termux-Killer.git && cd Termux-Killer && bash Tkiller.sh")
elif k == "24" :
               print("Installing Termux-Lazyscript... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install python python2 -y && cd && git clone https://github.com/TechnicalMujeeb/Termux-Lazyscript.git && cd Termux-Lazyscript && chmod +x * && bash setup.sh python2 ls.py")
elif k == "25" :
               print("Installing Termux-login... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/Ublimjo/Termux-login.git && cd Termux-login && bash setup.sh")
elif k == "26" :
               print("Installing Termux-speak... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python2 -y && cd && git clone https://github.com/TechnicalMujeeb/Termux-speak.git && cd Termux-speak && chmod +x * && python2 t-speak.py")
elif k == "27" :
               print("Installing Th3inspector... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git perl -y && cd && git clone https://github.com/Moham3dRiahi/Th3inspector.git cd Th3inspector chmod +x install.sh && ./install.sh")
elif k == "28" :
               print("Installing T-LOAD... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/noob-hackers/T-LOAD.git && cd T-LOAD && bash t-load.sh")
elif k == "29" :
               print("Installing TM-scanner... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python2 -y && git clone https://github.com/TechnicalMujeeb/TM-scanner.git && cd TM-scanner && chmod +x * && bash install.sh && python2 tmscanner.py")
elif k == "30" :
               print("Installing TermDistro... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/singhvijayp/TermDistro.git && cd TermDistro && python distro.py")
elif k == "31" :
               print("Installing Virus4... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && pkg install git python python2 -y && cd && git clone https://github.com/amerlaceset/Virus4.git && chmod +x * && python2 Virus4.py")
elif k == "32" :
               print("Installing X-Attack... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/CharlieTheHack1/X-Attack.git && cd X-Attack && chmod +x * && python2 X-Attack.py")
elif k == "33" :
               print("Installing anon-trap... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd anon-trap && python anontrap.py")
elif k == "34" :
               print("Installing blackeye... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd &&  git clone https://github.com/8L4NK/blackeye.git && cd blackeye && bash blackeye.sh")
elif k == "35" :
               print("Installing excuseme... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git php -y && cd && git clone https://github.com/CrackerCat/excuseme.git && cd excuseme && ")
elif k == "36" :
               print("Installing facebash... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/arashsofts/facebash.git && cd facebash && ./facebash.sh")
elif k == "37" :
               print("Installing fish... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install fish -y && fish")
elif k == "38" :
               print("Installing grabcam... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/noob-hackers/grabcam.git && cd grabcam && pip install lolcat && bash grabcam.sh")
elif k == "39" :
               print("Installing hacklock... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/noob-hackers/hacklock.git && cd hacklock && pip install lolcat && bash hacklock.sh")
elif k == "40" :
               print("Installing hammer... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/cyweb/hammer.git && cd hammer && python hammer.py")
elif k == "41" :
               print("Installing inshackle... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git openssl-tool -y && cd && git clone https://github.com/xd20111/inshackle.git && cd inshackle && bash inshackle.sh")
elif k == "42" :
               print("Installing instahack... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/Sanif007/instahack.git && cd instahack && pip install requests && pip install beautifulsoup4 && python instahack.py")
elif k == "43" :
               print("Installing instashell")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python openssl curl -y && cd && git clone https://github.com/g0r60n/InstaShell.git && cd InstaShell && ./instashell.sh")
elif k == "44" :
               print("Installing ipdrone... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/noob-hackers/ipdrone.git && cd ipdrone && pip install requests && python ipdrone.py")
elif k == "45" :
               print("Installing kalimux... ")
               time.sleep(3)
               os.system("clear")
               time,sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/noob-hackers/kalimux.git && cd kalimux && sh kalimux.sh")
elif k == "46" :
               print("Installing lazybee... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install python2 python git -y && cd && git clone https://github.com/noob-hackers/lazybee.git && cd lazybee && python2 lazybee.py")
elif k == "47" :
               print("Installing lazymux... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/Gameye98/Lazymux.git && cd Lazymux && python lazymux.py ")
elif k == "48" :
               print("Installing locator... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/yuhisern7/locator.git && cd locator && bash locator.sh")
elif k == "49" :
               print("Installing lockphish... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/JasonJerry/lockphish.git && cd lockphish && bash lockphish.sh")
elif k == "50" :
               print("Installing metasploit... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && pkg install unstable-repo x11-repo metasploit -y && msfconsole")
elif k == "51" :
               print("Installing mr.tracker... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/Sanif007/mr.tracker.git && cd mr.tracker && python mr.tracker.py")
elif k == "52" :
               print("Installing m-wiz... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && pip install lolcat && git clone https://github.com/noob-hackers/m-wiz.git && cd m-wiz && bash m-wiz.sh")
elif k == "53" :
               print("Installing nexphisher...")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/htr-tech/nexphisher.git && cd nexphisher && bash nexphisher")
elif k == "54" :
               print("Installing ohmyzsh... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/ohmyzsh/ohmyzsh.git && cd ohmyzsh && bash oh-my-zsh.sh")
elif k == "55" :
               print("Installing p-gen... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/noob-hackers/p-gen.git && cd p-gen && python p-gen.py")
elif k == "56" :
               print("Installing routersploit... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && pip2 install && git clone https://github.com/threat9/routersploit.git && cd routersploit && pip install future && pip2 install -r requirements-dev.txt && python rsf.py")
elif k == "57" :
               print("Installing sayhello... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/d093w1z/sayhello.git && cd sayhello && bash sayhello.sh")
elif k == "58" :
               print("Installing seeker... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/thewhiteh4t/seeker.git && cd seeker && chmod 777 termux_install.sh && ./termux_install.sh")
elif k == "59" :
               print("Installing shellphish... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/suljot/shellphish.git && cd shellphish && bash shellphish.sh")
elif k == "60" :
               print("Installing sms-scammer... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python -y && cd && git clone https://github.com/sanif007/sms-scammer.git && cd sms-scammer && python sms.py")
elif k == "61" :
               print("Installing sqlmap... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/sqlmapproject/sqlmap.git && cd sqlmap && python sqlmap.py -h")
elif k == "62" :
               print("Installing tmvenom... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/TechnicalMujeeb/tmvenom.git && cd tmvenom && python2 tmvenom2.py")
elif k == "63" :
               print("Installing Phonesploit... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/singhvijayp/PhoneSploit.git && cd PhoneSploit && bash ps.sh")
elif k == "64" :
               print("Installing tweetshell... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git tor -y && cd && git clone https://github.com/Mehran/tweetshell.git && cd tweetshell && ./tweetshell.sh")
elif k == "65" :
               print("Installing userrecon... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/singhvijayp/userrecon.git && cd userrecon && bash userrecon.sh")
elif k == "66" :
               print("Installing websploit... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && pip install --upgrade pip && pip2 install scapy && git clone https://github.com/websploit/websploit.git && cd websploit chmod 777 websploit && python2 websploit")
elif k == "67" :
               print("Installing weeman... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python2 -y && cd && https://github.com/evait-security/weeman.git && cd weeman && python2 weeman.py")
elif k == "68" :
               print("Installing wifite... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/derv82/wifite.git && cd wifite && chmod +x wifite.py && ./wifite.py")
elif k == "69" :
               print("Installing wifite2... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git python python2 -y && cd && git clone https://github.com/derv82/wifite2.git && cd wifite2 && python2 setup.py && python2 Wifite.py")
elif k == "70" :
               print("Installing zphisher... ")
               time.sleep(3)
               os.system("clear")
               time.sleep(2)
               os.system("apt update && apt upgrade -y && apt install git -y && cd && git clone https://github.com/htr-tech/zphisher.git && cd zphisher && bash zphisher.sh")
elif k=="00" or k == "0" :
    print("Thanks for using this tool :) ")
    time.sleep(2)
    exit()
else :
    print(" \033[1;31mERROR... \033[0;0mRestarting... ")
    os.system("python termtools.py")
